// Generated by gencpp from file command_pkg/sermon.msg
// DO NOT EDIT!


#ifndef COMMAND_PKG_MESSAGE_SERMON_H
#define COMMAND_PKG_MESSAGE_SERMON_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace command_pkg
{
template <class ContainerAllocator>
struct sermon_
{
  typedef sermon_<ContainerAllocator> Type;

  sermon_()
    : advice()
    , speed(0)  {
    }
  sermon_(const ContainerAllocator& _alloc)
    : advice(_alloc)
    , speed(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _advice_type;
  _advice_type advice;

   typedef int64_t _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::command_pkg::sermon_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::command_pkg::sermon_<ContainerAllocator> const> ConstPtr;

}; // struct sermon_

typedef ::command_pkg::sermon_<std::allocator<void> > sermon;

typedef boost::shared_ptr< ::command_pkg::sermon > sermonPtr;
typedef boost::shared_ptr< ::command_pkg::sermon const> sermonConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::command_pkg::sermon_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::command_pkg::sermon_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::command_pkg::sermon_<ContainerAllocator1> & lhs, const ::command_pkg::sermon_<ContainerAllocator2> & rhs)
{
  return lhs.advice == rhs.advice &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::command_pkg::sermon_<ContainerAllocator1> & lhs, const ::command_pkg::sermon_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace command_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::command_pkg::sermon_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::command_pkg::sermon_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::command_pkg::sermon_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::command_pkg::sermon_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::command_pkg::sermon_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::command_pkg::sermon_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::command_pkg::sermon_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b5fad3c1c2010335da2f9cba98fcf299";
  }

  static const char* value(const ::command_pkg::sermon_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb5fad3c1c2010335ULL;
  static const uint64_t static_value2 = 0xda2f9cba98fcf299ULL;
};

template<class ContainerAllocator>
struct DataType< ::command_pkg::sermon_<ContainerAllocator> >
{
  static const char* value()
  {
    return "command_pkg/sermon";
  }

  static const char* value(const ::command_pkg::sermon_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::command_pkg::sermon_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string advice\n"
"int64 speed\n"
;
  }

  static const char* value(const ::command_pkg::sermon_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::command_pkg::sermon_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.advice);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sermon_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::command_pkg::sermon_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::command_pkg::sermon_<ContainerAllocator>& v)
  {
    s << indent << "advice: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.advice);
    s << indent << "speed: ";
    Printer<int64_t>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMAND_PKG_MESSAGE_SERMON_H
